title: Accessibility for Teams
description: Guidelines to help teams create accessible and inclusive projects
imagepath: "/assets/img/lib/uswds/"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
