title: Accessibility for Teams
description: Guidelines to help teams create accessible products and services
imagepath: "/assets/img/lib/uswds/"
google_analytics: 'UA-121201150-1'

#TO UPDATE BEFORE MERGE/LAUNCH:
url: https://federalist-ed9ac7ce-8870-4699-95f8-e85f8b3c15b8.app.cloud.gov/preview/gsa/accessibility-for-teams/sitemap/

# Assets settings
sass:
  sass_dir: assets/stylesheets/site/
  style: compressed

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

